channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=20.3.3
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - pandas==1.2.3
  - psutil==5.9.4
  - scikit-learn==0.24.1
  - scipy==1.10.1
name: mlflow-env
