name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.24.0
  - pip=20.3.3
  # - mlflow=1.14.1
  - mlflow=2.2.2
  - hydra-core=1.0.6
  - pip:
      - wandb==0.14.0
      - hydra-joblib-launcher==1.1.2
